 CREATE TYPE "public"."equipment_type" AS ENUM('Classic/Raw', 'Equipped', 'both');--> statement-breakpoint
CREATE TYPE "public"."gender_type" AS ENUM('male', 'female', 'non-binary', 'prefer-not-to-say');--> statement-breakpoint
CREATE TYPE "public"."payment_statuses" AS ENUM('paid', 'unpaid', 'overdue');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('pending', 'completed', 'overdue');--> statement-breakpoint
CREATE TABLE "athletes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "athletes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"coachId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255),
	"gender" "gender_type" NOT NULL,
	"date_of_birth" date NOT NULL,
	"phoneNumber" varchar(11),
	"country" varchar(100),
	"city" varchar(100),
	"province" varchar(100),
	"timezone" varchar(100),
	"equipment" "equipment_type",
	"pr_squat" numeric(4, 1),
	"pr_bench" numeric(4, 1),
	"pr_deadlift" numeric(4, 1),
	"pr_total" numeric(5, 1),
	"meet_pr_squat" numeric(4, 1),
	"meet_pr_bench" numeric(4, 1),
	"meet_pr_deadlift" numeric(4, 1),
	"meet_pr_total" numeric(5, 1),
	"link" varchar(200),
	"joined_at" date NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true,
	"deleted" boolean DEFAULT false,
	"deleted_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "athletes_and_competitions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "athletes_and_competitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"athleteId" integer NOT NULL,
	"coachId" integer NOT NULL,
	"compId" integer NOT NULL,
	"date" date,
	"weigh_in_time" time,
	"equipment" "equipment_type",
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "coach_tasks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coach_tasks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"coach_id" integer NOT NULL,
	"athlete_id" integer,
	"training_block_id" integer,
	"title" varchar(255) NOT NULL,
	"description" varchar(255) NOT NULL,
	"due_date" date,
	"completed" boolean DEFAULT false NOT NULL,
	"status" "task_status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "coaches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "coaches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "coaches_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "competitions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "competitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255),
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"country" varchar(100),
	"city" varchar(100),
	"province" varchar(100),
	"link" varchar(200),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"athleteId" integer NOT NULL,
	"coachId" integer NOT NULL,
	"amount_in_cad" numeric(5, 2),
	"due_date" date NOT NULL,
	"payment_status" "payment_statuses" DEFAULT 'unpaid' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "training_blocks" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_blocks_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"athleteId" integer NOT NULL,
	"coachId" integer NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"last_update" date NOT NULL,
	"days_till_updates" integer NOT NULL,
	"send_post_block_overview_reminder" boolean DEFAULT false,
	"link" varchar(200),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- DROP TABLE "demo_users" CASCADE;--> statement-breakpoint
ALTER TABLE "athletes" ADD CONSTRAINT "athletes_coachId_coaches_id_fk" FOREIGN KEY ("coachId") REFERENCES "public"."coaches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "athletes_and_competitions" ADD CONSTRAINT "athletes_and_competitions_athleteId_athletes_id_fk" FOREIGN KEY ("athleteId") REFERENCES "public"."athletes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "athletes_and_competitions" ADD CONSTRAINT "athletes_and_competitions_coachId_coaches_id_fk" FOREIGN KEY ("coachId") REFERENCES "public"."coaches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "athletes_and_competitions" ADD CONSTRAINT "athletes_and_competitions_compId_competitions_id_fk" FOREIGN KEY ("compId") REFERENCES "public"."competitions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_tasks" ADD CONSTRAINT "coach_tasks_coach_id_coaches_id_fk" FOREIGN KEY ("coach_id") REFERENCES "public"."coaches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_tasks" ADD CONSTRAINT "coach_tasks_athlete_id_athletes_id_fk" FOREIGN KEY ("athlete_id") REFERENCES "public"."athletes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "coach_tasks" ADD CONSTRAINT "coach_tasks_training_block_id_training_blocks_id_fk" FOREIGN KEY ("training_block_id") REFERENCES "public"."training_blocks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_athleteId_athletes_id_fk" FOREIGN KEY ("athleteId") REFERENCES "public"."athletes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_coachId_coaches_id_fk" FOREIGN KEY ("coachId") REFERENCES "public"."coaches"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "training_blocks" ADD CONSTRAINT "training_blocks_athleteId_athletes_id_fk" FOREIGN KEY ("athleteId") REFERENCES "public"."athletes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "p" ADD CONSTRAINT "training_blocks_coachId_coaches_id_fk" FOREIGN KEY ("coachId") REFERENCES "public"."coaches"("id") ON DELETE restrict ON UPDATE no action;